In [1]:
import geopandas as gpd

In [9]:
ob = gpd.read_file(r"C:\Users\zigao\OneDrive - Univerza v Ljubljani\Documents\Nova mapa\Gurs_Arso_gikl\OB\OB.shp")
out_dir = r"C:\Users\zigao\OneDrive - Univerza v Ljubljani\Documents\Nova mapa\Gurs_Arso_gikl\OB\obcine_posamezno"

In [15]:
for index, row in ob.iterrows():
    # Create a GeoDataFrame with the current row
    gdf = gpd.GeoDataFrame([row], geometry="geometry", crs=ob.crs)
    
    # Extract the value from the "ID" column for the filename
    filename = row["OB_UIME"]
    
    # Construct the output file path for the shapefile
    output_file = f"{out_dir}/{filename}.shp"  # Use / as directory separator
    
    # Save the GeoDataFrame to a shapefile
    gdf.to_file(output_file)

In [14]:
ob.head()

,ENOTA,OB_MID,OB_ID,OB_UIME,OB_TIP,POV_KM2,D_OD,DV_OD,STATUS,CEN_E,CEN_N,geometry
0,OB,11026923,40,Izola,N,28.50,2015-02-25,2015-02-25,V,395487.0,45087.0,"POLYGON ((394273.002 44593.853, 394286.002 446..."
1,OB,11027776,50,Koper,D,303.50,2015-02-25,2015-02-25,V,400787.0,45967.0,"POLYGON ((402458.404 51516.555, 402574.592 514..."
2,OB,11027997,90,Piran,N,43.50,2015-02-25,2015-02-25,V,388317.0,44187.0,"POLYGON ((387969.019 44395.363, 387992.800 443..."
3,OB,24063526,213,Ankaran,N,8.04,2015-02-25,2015-02-25,V,401507.0,49597.0,"POLYGON ((399117.249 51162.701, 399161.274 511..."
4,OB,11026516,1,Ajdovščina,N,245.46,1995-01-01,1995-01-01,V,414738.0,83647.0,"POLYGON ((417272.799 90034.925, 417286.220 900..."